title = 'pycq'
description = 'Simple distributed FIFO queue for CockroachDB/PostgreSQL in Python'
url = 'https://github.com/adrianchifor/pycq'
version = '0.1.1'
author = 'Adrian Chifor'
author_email = 'me@adrianchifor.com'
license = 'Apache License 2.0'
