title = 'pycq'
description = 'Simple distributed FIFO queue for Python using CockroachDB/PostgreSQL'
url = 'https://github.com/adrianchifor/pycq'
version = '0.3.0'
author = 'Adrian Chifor'
author_email = 'me@adrianchifor.com'
license = 'Apache License 2.0'
